- name: Run commands with shell
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt:
        name:
         - nginx
        state: latest
        cache_valid_time: 3600
    - name: "Modifying index.html"
      lineinfile:
        path: /var/www/html/index.nginx-debian.html
        insertafter: '^<p><em>' 
        line: <h1>Archivo modificado por Ramon Ramos Tristan</h1> 
